INSERT INTO
  `users` (
    `id`,
    `username`,
    `name`,
    `password`,
    `plan_id`,
    `permission_id`,
    `reset_date`,
    `expire_date`,
    `auto_renew`,
    `rule`,
    `nat_rule`,
    `traffic`,
    `traffic_used`,
    `speed`,
    `maxconn`,
    `balance`,
    `price`,
    `cycle`,
    `permission`,
    `api_token`,
    `last_ip`,
    `last_active`,
    `registration_date`
  )
VALUES
  (
    NULL,
    'admin',
    'Admin',
    '21232f297a57a5a743894a0e4a801fc3',
    '0',
    '0',
    '0000-00-00',
    '0000-00-00',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0.00',
    '0.00',
    '0',
    '2',
    '',
    '',
    '0000-00-00 00:00:00.000000',
    CURRENT_TIMESTAMP
  );

INSERT INTO
  `settings` (`id`, `name`, `value`)
VALUES
  (NULL, 'version', ''),
  (NULL, 'system_url', ''),
  (NULL, 'license', ''),
  (NULL, 'secure_key', ''),
  (NULL, 'certificate', ''),
  (NULL, 'certificate_key', ''),
  (NULL, 'register', 'false'),
  (NULL, 'register_recaptcha', 'false'),
  (NULL, 'recaptcha_public', ''),
  (NULL, 'recaptcha_private', '');

INSERT INTO
  `payments` (`id`, `type`, `name`, `value`)
VALUES
  (NULL, 'whmcs', 'enable', 'false'),
  (NULL, 'whmcs', 'display', 'WHMCS'),
  (NULL, 'whmcs', 'fee', ''),
  (NULL, 'whmcs', 'api', ''),
  (NULL, 'whmcs', 'secret', ''),
  (NULL, 'alipay_qr', 'enable', 'false'),
  (NULL, 'alipay_qr', 'display', '支付宝'),
  (NULL, 'alipay_qr', 'fee', ''),
  (NULL, 'alipay_qr', 'appid', ''),
  (NULL, 'alipay_qr', 'public_key', ''),
  (NULL, 'alipay_qr', 'private_key', ''),
  (NULL, 'epay', 'enable', 'false'),
  (NULL, 'epay', 'display', '易支付'),
  (NULL, 'epay', 'fee', ''),
  (NULL, 'epay', 'api', ''),
  (NULL, 'epay', 'id', ''),
  (NULL, 'epay', 'key', ''),
  (NULL, 'epay', 'methods', ''),
  (NULL, 'usdt_trc20', 'enable', 'false'),
  (NULL, 'usdt_trc20', 'display', 'USDT TRC20'),
  (NULL, 'usdt_trc20', 'fee', ''),
  (NULL, 'usdt_trc20', 'api', ''),
  (NULL, 'usdt_trc20', 'token', ''),
  (NULL, 'mgate', 'enable', 'false'),
  (NULL, 'mgate', 'display', 'MGate'),
  (NULL, 'mgate', 'fee', ''),
  (NULL, 'mgate', 'api', ''),
  (NULL, 'mgate', 'app_id', ''),
  (NULL, 'mgate', 'app_secret', '');